### ISSUE TITLE
http-to-https-proxy on Raspberry Pi

### ISSUE THREAD

**Issue by gadjodilo83** [yeokm1/http-to-https-proxy#1]
Hi!

i have a problem to connect my doschGPT with my Raspberry Pi. When i start the http-to-https-proxy on a Windows machine it works like a charm. :) But my Raspberry Pi wont work with my http-to-https-proxy...

Here my screenshots:
![image](https://user-images.githubusercontent.com/16428002/235492942-c2ad37b9-5c7c-4adf-bd9b-a5b2d267a1b9.png)

![image](https://user-images.githubusercontent.com/16428002/235493422-faf98321-12f9-4386-9eb0-dd3520d70ea4.png)

i'm using the https-proxy-linux-**arm** version...

Maybe you can help me :)

Thanks  from Switzerland
Marc

**Comment by yeokm1** [comment]
Hi Marc

This is interesting as you are the first person to report an issue with the proxy itself. 

Can you pass me the following information so I can try replicate the problem.

1. Which Raspberry Pi Model is this?
2. What operating system distribution and version is it running on? Like Debian, Ubuntu, etc?
3. How long is the delay pressing Enter on the DOS client before it times out?

**Comment by gadjodilo83** [comment]
Hi

Thanks for the answer, here are my informations:

-Raspberry Pi 4 Model B Rev 1.1
-Linux homePI 4.19.75-v7l+ BST 2019 armv7l GNU/Linux | "Raspbian GNU/Linux 10 (buster)"
-Like the standard timeout 40sec
-i'm using DosGPT [v0.10]

Thanks! :)

**Comment by yeokm1** [comment]
That's great to hear! :)

By the way, just informing that there is a newer release of Doschgpt at v0.11. It additionally supports the Hugging Face API which is an open source alternative and (currently) free too. Do give it a try as well if you wish.
